package com.example.hotel.controller.command;

public enum CommandName {
    LOGIN,
    LOGOUT,
    REGISTER,
    SEARCH,
    ORDER,
    PROCESS_ORDER,
    CANCEL_ORDER,
    RESERVE,
    PAY,
    CANCEL_RESERVATION,
    SET_LOCALE,
    CANCEL_PAYMENT,
    UPDATE_FAILED_PAYMENTS  ,

    GET_LOGIN_PAGE,
    GET_REGISTER_PAGE,
    GET_MAIN_PAGE,
    GET_APARTMENT_PAGE,
    GET_ORDER_PAGE,
    GET_CLIENT_PROFILE_PAGE,
    GET_ORDER_PROCESSING_PAGE,
    GET_ALL_ORDERS_PAGE,
    GET_ALL_RESERVATIONS_PAGE,
    GET_ALL_PAYMENTS_PAGE
}
